package is.bokun.dtos.pricing;

public enum CostItemTypeEnum {

    ROOM_TYPE,
    PRICING_CATEGORY,
    DEPARTURE_PRICING_CATEGORY,
    VEHICLE_TYPE,
    PICKUP,
    DEPARTURE_PICKUP,
    DROPOFF,
    DEPARTURE_DROPOFF,
    PICKUP_AND_DROPOFF,
    ROUTELEG_PASSENGER_CATEGORY,
    ROUTELEG_PASSENGER_CATEGORY_PEAK,
    ROUTELEG_PASSENGER_CATEGORY_FARECLASS,
    ROUTELEG_PASSENGER_CATEGORY_FARECLASS_PEAK,
    EXTRA
}
